### PR TITLE
Newsletter fixes

### LINKED ISSUE #5865: [bug]: Newsletters are 404 missing on freesewing.org
### What seems to be the problem? 🤔

On the Newsletter web page (https://freesewing.org/newsletter), all of the links to individual newsletters lead to 404 missing web pages.

For example, the web page for the 2024 Q1 newsletter is missing:  https://freesewing.org/newsletter/2024q1

### Design / Plugin / Package 🧐

_No response_

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

### Additional context

_No response_

### LINKED ISSUE #5881: [bug]: /welcome/newsletter has small typo
Hei,

you landing page at /welcome/newsletter has tiny typo "Would you like to reveice the FreeSewing newsletter?"
I'm bit tired so no energy to dive into your code and submit PR, rather this simple report.
Maybe another day I could go down to the code ;)

[User 65843](https://next.freesewing.org/users/65843)

### PR DESCRIPTION
**Pull request by VSinerva**
Closes #5865 by having a minimal working view for newsletters on the website (copied almost directly from the one for showcases :wink:).

The missing image icon and missing author warnings could be cleaned up, but I did not consider that to be critical for these pages.

Also fixes a typo in the settings and removes a duplicate paragraph when logged in and viewing `/newsletter`.

Edit: Also closes #5881 which was coincidentally opened after the creation of this PR

### CODE REVIEW

**Review by BenJamesBen — APPROVED** [review]
I tested this PR in the localhost org site (`yarn kickstart ; cd sites/org ; yarn start`), and confirmed that the newsletters appear properly.
Screenshot 2024-01-23 at 10 00 43 AM

I also confirmed that the duplicate paragraph issue is fixed:

Before:
Screenshot 2024-01-23 at 3 03 27 PM

After:
Screenshot 2024-01-23 at 3 02 56 PM

File: sites/org/pages/newsletter/[dir].mjs [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+      title={frontmatter.title}
+      intro={frontmatter.intro}
+      layout={(props) => (
+        <PostLayout
+          {...props}
+          slug={page.path.join('/')}
+          frontmatter={frontmatter}
+          mdx={mdx}
+          dir={dir}
+          type="newsletter"
```
Comment (joostdecock) [inline sites/org/pages/newsletter/[dir].mjs:23]: Since we're passing the type here, we should update the `PostLayout` component to not show an image for newsletter posts (since they don't have one).

Can you update `sites/org/components/layouts/post.mjs` so that line 93 looks like this:

```mjs
{type === 'newsletter' 
  ? null 
  : <PostImage imgId={`${type}-${dir}`} frontmatter={frontmatter} />
}
```

That will keep the (currently broken) image out of the view.

Apart from that, this is great.

Comment (VSinerva) [reply sites/org/pages/newsletter/[dir].mjs:23]: Done!

**Review by aytvill — APPROVED** [review]
trivial fix of typo in text

**Review by BenJamesBen — APPROVED** [review]
I tested the updated PR localhost org site and the newsletter still looks fine, with the missing image now omitted.

Screenshot 2024-01-25 at 10 29 45 PM

**Review by joostdecock — APPROVED** [review]
