### PR TITLE
fix(workbench): Allow blank optional measurements

### LINKED ISSUE #3973: [bug]: Cannot clear optional measurements once entered in the lab UI
### What seems to be the problem? 🤔

In the lab UI, once optional measurements are entered for a pattern, it is not possible to remove or clear them.

Steps to Reproduce:
1. In either the localhost development environment or lab.freesewing.dev, browse to the Unice design.
2. Select a model to pre-populate the measurements.
3. Switch to DraftDesign view.
4. Switch back to Measurements view, and delete the optional Cross Seam and Cross Seam Front measurements.
5. Switch to DraftDesign view.
6. Switch back to Measurements view, and observe that the deleted measurements re-appeared.
7. Use ClearThing to reset the pattern.
8. In Measurements view, enter all the required measurements, but leave the two optional measurements blank.
9. Switch to DraftDesign view, and observe that the pattern drafts just fine without the optional measurements.
10. Switch back to Measurements view and observe that the optional measurements are blank.
11. Enter the 2 optional measurements.
12. Switch to DraftDesign view.
13. Switch back to Measurements view, and delete the optional Cross Seam and Cross Seam Front measurements.
14. Switch to DraftDesign view.
15. Switch back to Measurements view, and observe that the deleted measurements re-appeared.

A workaround is to use ClearThing to clear all the measurements, but this can require the user to re-enter all the required measurements again manually.

### Design / Plugin / Package 🧐

_No response_

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BenJamesBen**
Fixes #3973.

I don't know if this is an appropriate way or the best way to fix the issue. This PR adds an `optional` parameter allows zero values if optional. (From testing I observed that the value is set to zero when the field is blanked out.)

### CODE REVIEW

File: sites/shared/components/workbench/inputs/measurement.mjs [hunk 1]
```diff
@@ -11,16 +11,18 @@ import { measurementAsMm } from 'shared/utils.mjs'
...
   const title = t(`measurements:${m}`)
 
   const isDegree = isDegreeMeasurement(m)
   const factor = useMemo(() => (isDegree ? 1 : gist.units == 'imperial' ? 25.4 : 10), [gist.units])
 
-  const isValValid = (val) =>
-    typeof val === 'undefined' || val === '' ? null : val != false && !isNaN(val)
+  const isValValid = (val) => {
+    if (optional && val === 0) return true
+    return typeof val === 'undefined' || val === '' ? null : val != false && !isNaN(val)
```
Comment (eriese) [inline sites/shared/components/workbench/inputs/measurement.mjs:24]: I would just replace these lines with `return val  == false ? optional : !isNaN(val)` because `undefined`, `0`, and `''` are all falsy, and any of them should be allowed on an optional measurement

File: sites/shared/components/workbench/inputs/measurement.mjs [hunk 2]
```diff
@@ -11,16 +11,18 @@ import { measurementAsMm } from 'shared/utils.mjs'
...
  * measurement and I always have some typo in it because dyslexia.
  */
-export const MeasurementInput = ({ m, gist, app, updateMeasurements, focus }) => {
+export const MeasurementInput = ({ m, gist, app, updateMeasurements, focus, optional }) => {
   const { t } = useTranslation(['app', 'measurements'])
   const prefix = app.site === 'org' ? '' : 'https://freesewing.org'
   const title = t(`measurements:${m}`)
 
   const isDegree = isDegreeMeasurement(m)
   const factor = useMemo(() => (isDegree ? 1 : gist.units == 'imperial' ? 25.4 : 10), [gist.units])
```
Comment (eriese) [inline sites/shared/components/workbench/inputs/measurement.mjs:20]: I know it's not in the scope of the PR, but while you're here can you please fix these lint warnings? If fixing them messes everything up we can bump it to the workbench refactor

**Review by eriese — CHANGES_REQUESTED** [review]

File: sites/shared/components/workbench/inputs/measurement.mjs (hunk 2 above)
Comment (BenJamesBen) [reply sites/shared/components/workbench/inputs/measurement.mjs]: I believe that I eliminated the `eslint` warnings in a way that is correct. I had to add more `useCallback()` hooks to deal with additional `eslint` warnings that popped up due to the changes.

File: sites/shared/components/workbench/inputs/measurement.mjs (hunk 1 above)
Comment (BenJamesBen) [reply sites/shared/components/workbench/inputs/measurement.mjs]: Replaced code as suggested.

**Review by eriese — APPROVED** [review]
