### PR TITLE
Fix issue #7123 (Opal strap taper position calculation bug)

### LINKED ISSUE #7123: [bug]: Opal calculates intersection between two parallel vertical beams
### What seems to be the problem? 🤔

When I generate an Opal and increase the **Back bib base angle** option to 90 degrees, the design tries to calculate a beam intersection between these 4 points in back.mjs line 124
```
  points.bibCurveMax = utils.beamsIntersect(
    points.waist,
    points.waist.shift(180 - options.backBibBaseAngle, 9001),
    points.bibHexagonLowerInside,
    points.bibHexagonUpperInside
  )
```

these are the values of the 4 points in my browser console:

```
Object { x: 0, y: -49.5, attributes: {…}, name: "waist", … }
 
Object { x: 1.6534568758687989e-12, y: -9050.5, attributes: {…}, … }
 
Object { x: -108.43749999999997, y: -220, attributes: {…}, name: "bibHexagonLowerInside", … }
 
Object { x: -108.43749999999997, y: -280, attributes: {…}, name: "bibHexagonUpperInside", … }
```

As you can see, these are both (almost) vertical lines, which causes stability problems in the calculation and crash the site (especially after applying https://github.com/freesewing/freesewing/pull/7122, which adds a missing check for intersecting two vertical beams).

### Design / Plugin / Package 🧐

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Thrunic**
Closes #7123

### CODE REVIEW

File: designs/opal/src/back.mjs [hunk 1]
```diff
@@ -136,11 +136,10 @@ function draftBack({
     options.backBibBaseCurve
   )
 
-  points.strapTaperCurveMax = utils.beamsIntersect(
+  points.strapTaperCurveMax = utils.beamIntersectsX(
```
Comment (HaasJona) [inline designs/opal/src/back.mjs:139]: Looks good to me, no issues anymore when ran with the changes in #7137

**Review by HaasJona — APPROVED** [review]

**Comment by BenJamesBen** [comment]
I tested this PR in the org development environment. However, because this PR already includes PR #7128, I was not able to test whether this PR fixes the Back bib base angle issue of #7123. And the Strap taper position issue of #7123 does not appear on freesewing.org, so I am not able to test that aspect of this PR either.

**Review by joostdecock — APPROVED** [review]
